name: Build EXE for Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp pyinstaller

      - name: Build EXE C贸 Console
        run: |
          pyinstaller --onefile --console yt_dlp_gui.py
        shell: cmd

      - name: Build EXE Kh么ng Console
        run: |
          pyinstaller --onefile --noconsole yt_dlp_gui.py
        shell: cmd

      - name: Upload EXE C贸 Console
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/yt_dlp_gui.exe
          asset_name: yt_dlp_gui_console.exe
          asset_content_type: application/octet-stream

      - name: Upload EXE Kh么ng Console
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/yt_dlp_gui.exe
          asset_name: yt_dlp_gui_no_console.exe
          asset_content_type: application/octet-stream
